# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'heart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for heart
   pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'



  target 'heartTests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!
 pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

    pod 'FirebaseUI/Google'
  

  end

  target 'heartUITests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!

    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Messaging'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'

  end

end
